---
- block:

  - name: 'supertty : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      dest: /opt/supertty
      force: yes
      repo: https://github.com/bad-hombres/supertty.git
      version: 8f800748f4ba9462df4917c4997fbf8146ee43ba

  - name: 'supertty : remove existing venv'
    file:
      path: /opt/supertty/.venv
      state: absent

  - name: 'supertty : create venv directory'
    file:
      path: /opt/supertty/.venv
      state: directory

  - name: 'supertty : initialise venv'
    shell: 'bash -lc "virtualenv -p python2 /opt/supertty/.venv"'

  - name: 'supertty : install docopt'
    pip:
      name: docopt
      state: present
      virtualenv: /opt/supertty/.venv

  - name: 'supertty : install launcher'
    template:
      dest: /usr/local/bin/supertty
      mode: 0755
      src: ../templates/supertty.sh

  tags:
    - maintening-access
    - supertty
