---
- block:
  - name: 'gittools : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/gittools
      force: yes
      repo: https://github.com/internetwache/GitTools.git

  - name: install gitfinder
    pip:
      requirements: requirements.txt
    args:
      chdir:
        /opt/gittools/Finder
      
  - name: 'install gitdumper'
    copy:
      src: /opt/gittools/Dumper/gitdumper.sh
      dest: /usr/local/bin/
      mode: 0755

  - name: 'install gitextractor'
    copy:
      src: /opt/gittools/Extractor/extractor.sh
      dest: /usr/local/bin/
      mode: 0755      

  tags:
  - exploitation-tools
  - gittools
