---
- include: shocker.yml tags=exploitation-tools,shocker
- include: crackmapexec.yml tags=exploitation-tools,crackmapexec
- include: gittools.yml tags=exploitation-tools,gittools
- include: cmseek.yml tags=exploitation-tools,cmseek
- include: thefatrat.yml tags=exploitation-tools,thefatrat
