---
- block:
  - name: 'TheFatRat : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/thefatrat
      force: yes
      repo: https://github.com/Screetsec/TheFatRat.git

  - name: 'TheFatRat : Change file permissions'
    file:
      path: /opt/thefatrat/setup.sh
      mode: +x   

  - name: 'TheFatRat : run installer'
    shell: './setup.sh'
    args:
      chdir: /opt/thefatrat  

  - name: 'TheFatRat : Change file permissions'
    file:
      path: /opt/thefatrat/fatrat
      mode: +x        

  - name: 'TheFatRat : Change file permissions'
    file:
      path: /opt/thefatrat/powerfull.sh
      mode: +x        

  - name: 'TheFatRat : install launcher'
    template:
      dest: /usr/local/bin/fatrat
      mode: 0755
      src: ../templates/thefatrat.sh

  tags:
  - exploitation-tools
  - thefatrat
