---
- block:
  - name: 'TheFatRat : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/thefatrat
      force: yes
      repo: https://github.com/Screetsec/TheFatRat.git

  - name: 'TheFatRat : Change file permissions'
    file:
      path: /opt/thefatrat/setup.sh
      mode: +x   

  - name: 'TheFatRat : Change file permissions'
    file:
      path: /opt/thefatrat/fatrat
      mode: +x        

  - name: 'TheFatRat : Change file permissions'
    file:
      path: /opt/thefatrat/powerfull.sh
      mode: +x        

  tags:
  - exploitation-tools
  - thefatrat
