---
- block:

  - name: 'pydictor : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/pydictor
      force: yes
      repo: https://www.github.com/landgrey/pydictor.git
      
  - name: 'pydictor : remove existing venv'
    file:
      path: /opt/pydictor/.venv
      state: absent

  - name: 'pydictor : create venv directory'
    file:
      path: /opt/pydictor/.venv
      state: directory

  - name: 'pydictor : initialise venv'
    shell: 'bash -lc "virtualenv -p python2 /opt/pydictor/.venv"'

  - name: 'pydictor : install docopt'
    pip:
      name: docopt
      state: present
      virtualenv: /opt/pydictor/.venv

  - name: 'pydictor : install launcher'
    template:
      dest: /usr/local/bin/pydictor
      mode: 0755
      src: ../templates/pydictor.sh

  tags:
    - dictionary-tools
    - pydictor
