---
- block:

  - name: get set
    git:
      repo: https://github.com/trustedsec/social-engineer-toolkit
      dest: /opt/set
      update: yes

  - name: install set
    shell: python setup.py install
    args:
      chdir: /opt/set

  tags:
    - social-engineering
    - set
