---
- block:
  - name: Create a directory if it does not exist
    file:
      path: /tmp/hyenae
      state: directory
      mode: '0755'
    
  - name: Download and unarchive hyenae
    unarchive:
      src: https://sourceforge.net/projects/hyenae/files/0.36-1/hyenae-0.36-1.tar.gz/download
      dest: /tmp/hyenae
      remote_src: yes

  - name: 'hyenae : configure'
    shell: 'bash -lc "/tmp/hyenae/configure"'
    args:
      chdir: /tmp/hyenae

  - name: 'hyenae : make'
    make:
      chdir: /tmp/hyenae

  - name: 'hyenae : make install'
    make:
      chdir: /tmp/hyenae
      target: install

  - name: 'hyenae : remove build fragments'
    file:
      path: /tmp/hyenae
      state: absent
      
  tags:
  - network-packet-generator
  - hyenae
