---
- block:
  - name: 'rootkithunter : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /tmp/rootkithunter
      force: yes
      repo: https://github.com/installation/rkhunter.git

  - name: 'rootkithunter : configure'
    shell: 'bash -lc "/tmp/rootkithunter/install.sh contact@nohackme.com"'
    args:
      chdir: /tmp/rootkithunter
      
  - name: 'rootkithunter : remove build fragments'
    file:
      path: /tmp/rootkithunter
      state: absent

  tags:
  - rootkit-detection
  - rootkithunter
