---
- block:
  - name: Create a directory if it does not exist
    file:
      path: /tmp/rkhunter
      state: directory
      mode: '0755'
    
  - name: Download and unarchive rkhunter
    unarchive:
      src: http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.2/rkhunter-1.4.2.tar.gz
      dest: /tmp/rkhunter
      remote_src: yes

  - name: 'rkhunter : configure'
    shell: 'bash -lc "./installer.sh --layout default --install"'
    args:
      chdir: /tmp/rkhunter/rkhunter-1.4.2
      
  - name: 'rkhunter : remove build fragments'
    file:
      path: /tmp/rkhunter
      state: absent

  tags:
  - rootkit-detection
  - rootkithunter
