---
- block:
  - name: 'rootkithunter : install package'
    apt:
      name: rkhunter
      state: present
      cache_valid_time: '{{ apt_cache_timeout }}'
      
  tags:
  - rootkit-detection
  - rootkithunter
