---
- block:
  - name: 'nessus : check for existing installation'
    stat: path=/etc/init.d/nessusd
    register: nessus
    
  - name: Create a directory if it does not exist
    file:
      path: /tmp/nessusinstall
      state: directory
      mode: '0755'
    
  - name: 'nessus : download installer'
    get_url:
      url: '{{ nessus_package }}'
      dest: /tmp/nessusinstall
      mode: 0755
    when: not nessus.stat.exists
    
  - name: 'nessus : run install'
    command: 'dpkg -i Nessus-*.deb'
    when: not nessus.stat.exists
    
  - name: 'nessus : start'
    command: '/etc/init.d/nessusd start'
    when: not nessus.stat.exists
    
  - name: 'nessus : automatic start'
    command: 'update-rc.d nessusd enable'
    when: not nessus.stat.exists

  tags:
  - vulnerability-analysis
  - nessus
