---
- block:
  - name: 'nessus : check for existing installation'
    stat: path=/etc/init.d/nessusd
    register: nessus
    
  - name: Create a directory if it does not exist
    file:
      path: /tmp/nessusinstall
      state: directory
      mode: '0755'
    when: not nessus.stat.exists
    
  - name: 'nessus : copy installer'
    copy:
      dest: /tmp/nessusinstall
      mode: 0755
      src: ../files/Nessus-8.4.0-debian6_amd64.deb
    when: not nessus.stat.exists
    
  - name: 'nessus : run install'
    command: 'dpkg -i /tmp/nessusinstall/Nessus-*.deb'
    when: not nessus.stat.exists
    
  - name: 'nessus : start'
    command: '/etc/init.d/nessusd start'
    when: not nessus.stat.exists
    
  - name: 'nessus : automatic start'
    command: 'update-rc.d nessusd enable'
    when: not nessus.stat.exists

  tags:
  - vulnerability-analysis
  - nessus
