---
- block:
   
  - name: Create a rips directory if it does not exist
  file:
    path: /var/www/html/rips
    state: directory
    mode: '0755'
    
  - name: Ansible check rips directory exists.
    stat:
      path: /var/www/html/rips
    register: rips_dir
    
  - name: 'rips : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /var/www/html/rips
      force: yes
      repo: https://github.com/ripsscanner/rips
    when: rips_dir.stat.exists and rips_dir.stat.isdir

  tags:
    - vulnerability-analysis
    - rips
