---
- block:

  - name: 'cupp : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/cupp
      force: yes
      repo: https://github.com/Mebus/cupp.git
      
  - name: 'cupp : remove existing venv'
    file:
      path: /opt/cupp/.venv
      state: absent

  - name: 'cupp : create venv directory'
    file:
      path: /opt/cupp/.venv
      state: directory

  - name: 'cupp : initialise venv'
    shell: 'bash -lc "virtualenv -p python2 /opt/cupp/.venv"'

  - name: 'cupp : install docopt'
    pip:
      name: docopt
      state: present
      virtualenv: /opt/cupp/.venv

  - name: 'cupp : install launcher'
    template:
      dest: /usr/local/bin/cupp
      mode: 0755
      src: ../templates/cupp.sh

  tags:
    - password-attacks
    - cupp
