---
- block:
  - name: 'pdfcrack : installation'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /tmp/pdfcrack
      force: yes
      repo: https://github.com/robins/pdfcrack.git

  - name: 'pdfcrack : make'
    make:
      chdir: /tmp/pdfcrack

  - name: 'pdfcrack : make install'
    make:
      chdir: /tmp/pdfcrack
      target: install

  - name: 'pdfcrack : remove build fragments'
    file:
      path: /tmp/pdfcrack
      state: absent

  tags:
  - password-attacks
  - pdfcrack
