---
- block:
  - name: Cloning repo
    git:
      repo: https://github.com/rbsec/sslscan.git
      dest: "/tmp/sslscan"
      update: yes
    register: sslscan

  - name: Installing dependencies
    when: ansible_os_family ==  "Debian" and sslscan.changed
    apt:
      name: ['build-essential', 'zlib1g-dev']
      update_cache: yes
      state: latest

  - name: Build dependencies
    when: ansible_os_family ==  "Debian" and sslscan.changed
    apt:
      pkg: openssl
      state: build-dep

  - name: 'sslscan : build (statically linked)'
    when: sslscan.changed
    make:
      chdir: /tmp/sslscan
      target: static

  - name: 'sslscan : install'
    when: sslscan.changed
    copy:
      dest: /usr/local/bin/sslscan
      mode: 0755
      remote_src: yes
      src: /tmp/sslscan/sslscan

  - name: 'sslscan : remove build fragments'
    when: sslscan.changed
    file:
      path: /tmp/sslscan
      state: absent

  tags:
  - information-gathering
  - sslscan
