---
- block:
  - name: 'tftptheft : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/tftptheft
      force: yes
      repo: https://github.com/EnableSecurity/tftptheft.git

  - name: 'tftptheft : remove existing venv'
    file:
      path: /opt/tftptheft/.venv
      state: absent

  - name: 'tftptheft : create venv directory'
    file:
      path: /opt/tftptheft/.venv
      state: directory

  - name: 'tftptheft : initialise venv'
    shell: 'bash -lc "virtualenv -p python3 /opt/tftptheft/.venv"'

  - name: 'tftptheft : install docopt'
    pip:
      name: docopt
      state: present
      virtualenv: /opt/tftptheft/.venv

  - name: 'thief : install launcher'
    template:
      dest: /usr/local/bin/thief
      mode: 0755
      src: ../templates/thief.sh

  - name: 'finder : install launcher'
    template:
      dest: /usr/local/bin/finder
      mode: 0755
      src: ../templates/finder.sh

  tags:
  - information-gathering
  - tftptheft
