---
- block:
  - name: 'deathstar : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/deathstar
      force: yes
      repo: https://github.com/byt3bl33d3r/DeathStar.git

  - name: install deathstar
    pip:
      requirements: requirements.txt
    args:
      chdir:
        /opt/deathstar
        
  - name: 'deathstar : add startup script'
    template:
      dest: /usr/local/bin/deathstar
      mode: 0755
      src: ../templates/deathstar.sh

  tags:
  - powershell
  - deathstar
