---
- block:
  - name: 'unicorn : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/unicorn
      force: yes
      repo: https://github.com/trustedsec/unicorn.git

  - name: 'unicorn : add startup script'
    template:
      dest: /usr/local/bin/unicorn
      mode: 0755
      src: ../templates/unicorn.sh

  tags:
  - powershell
  - unicorn
