---
- block:
  - name: 'Apps : install package'
    apt:
      name:
        - zsh
        - python3
        - python3-pip
        - python
        - python-pip
      state: present
      cache_valid_time: '{{ apt_cache_timeout }}'

  tags:
  - common
