---
- block:
  - name: 'Apps : install package'
    apt:
      name:
        - zsh
        - python3
        - python3-pip
        - python3-ipadress
        - python
        - python-pip
        - python-ipadress
      state: present
      cache_valid_time: '{{ apt_cache_timeout }}'
    ignore_errors: true

  tags:
  - common
