---
- block:
  - name: 'golang : check install'
    stat:
      path: /usr/local/go
    register: _check_golang

  - name: 'golang : download golang 1.12.4 archive'
    get_url:
      url: https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz
      dest: /tmp/golang.tar.gz
      checksum: sha256:d7d1f1f88ddfe55840712dc1747f37a790cbcaa448f6c9cf51bbe10aa65442f5
    when: _check_golang.stat.exists == False

  - name: 'golang : extract archive'
    unarchive:
      dest: /usr/local
      remote_src: yes
      src: /tmp/golang.tar.gz
    when: _check_golang.stat.exists == False

  - name: 'golang : add golang directory to $PATH'
    lineinfile:
      insertafter: EOF
      line: export PATH=$PATH:/usr/local/go/bin
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile
      - /etc/zsh/zprofile
    when: _check_golang.stat.exists == False

  - name: 'golang : setup $GOPATH'
    lineinfile:
      insertafter: EOF
      line: export GOPATH=/root/.go
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile
      - /etc/zsh/zprofile
    when: _check_golang.stat.exists == False

  - name: 'golang : setup $GOBIN'
    lineinfile:
      insertafter: EOF
      line: export GOBIN=$GOPATH/bin
      path: '{{ item }}'
      state: present
    with_items:
      - /etc/profile
      - /etc/zsh/zprofile
    when: _check_golang.stat.exists == False

  - name: 'golang : cleanup fragments'
    file:
      dest: /tmp/golang.tar.gz
      state: absent
    when: _check_golang.stat.exists == False

  tags:
  - common
  - golang
  - information-gathering
  - pspy
