---
- block:
  - name: 'lazyscript : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/lazyscript
      force: yes
      repo: https://github.com/arismelachroinos/lscript.git
      
  - name: 'lazyscript : Change file permissions'
    file:
      path: /opt/lazyscript/install.sh
      mode: +x
      
  - name: 'install lazyscript'
    shell: './install.sh'
    args:
      chdir:
        /opt/lazyscript

  tags:
  - frameworks
  - lazyscript
