---
- block:
  - name: 'wpxf : install prerequisites'
    apt:
      name:
        - build-essential
        - liblzma-dev
        - libsqlite3-dev
        - patch
        - zlib1g-dev
        - ruby-full
      state: present
      update_cache: yes

  - name: 'wpxf : install gem'
    shell: '/bin/bash -lc "gem install wpxf"'

  tags:
  - frameworks
  - wpxf
